name: flycolor
description: A Radix inspired color system for Flutter with perceptually uniform, contextually aware 12-step color scales.
version: 0.1.0
homepage: https://github.com/realflyui/flycolor
repository: https://github.com/realflyui/flycolor

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  okcolor: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
